/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CountDownTimer: typeof import('./src/components/tomato-card/components/countDownTimer.vue')['default']
    DataPane: typeof import('./src/components/data-pane/data-pane.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Heatmap: typeof import('./src/components/data-pane/components/heatmap.vue')['default']
    InputNumber: typeof import('./src/components/tomato-card/components/inputNumber.vue')['default']
    ProgressCard: typeof import('./src/components/progress-card/progress-card.vue')['default']
    Setting: typeof import('./src/components/setting/setting.vue')['default']
    SettingItem: typeof import('./src/components/setting/components/setting-item.vue')['default']
    TomatoCard: typeof import('./src/components/tomato-card/tomato-card.vue')['default']
  }
}
